### PR TITLE
Minor readme.txt changes

### PR DESCRIPTION
**Pull request by Synesso**
I found it needed sbt 0.13 installed. Also added the remaining examples to the readme.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @Synesso,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Typesafe Contributors License Agreement:

[http://typesafe.com/contribute/cla](http://typesafe.com/contribute/cla)

**Comment by Synesso** [comment]
CLA signed.

**Comment by szeiger** [comment]
That last commit shouldn't be there. You should use a separate branch for each PR to avoid these issues.

**Comment by Synesso** [comment]
Oops, sorry. I thought PRs were based on commit, not branch. I'll do this again when I'm on the right machine.

**Pull request closed without merging**
